# Welcome to Jekyll!

locale: "fr-FR"
title: "KOAN Kenjy"
email: kenjy.koan@gmail.com
description: >-
  Site personnel et partage de projets
baseurl: ""
url: "https://kenjykoan.fr"
repository: "kenjykoan/kenjykoan.github.io"
github_username:  kenjykoan
github: [metadata]
logo: "/_data/images/probability.png"
masthead_title: "Accueil - KOAN Kenjy"

# Build settings
markdown: kramdown

# Build settings
#theme: minima
remote_theme: "mmistakes/minimal-mistakes@4.26.1"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache

google-site-verification: "AL8rUca2rFCkz20V64waCnxBeMyJ1ZFkiUcuo7ivDbo"
include: ["_pages", "_data", "_layouts", "_blog"]
livereload: true

# collections:
#   teachings:
#     output: true
#     permalink: /:collection/:path/

collections:
  # reminders:
  #   output: true
  #   permalink: /:collection/:path/
  blog:
    output: true
    permalink: /:collection/:path/

# default configurations for each type
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      comments: true
      share: true
      author_profile: true
      classes: wide

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

  # _blog
  - scope:
      path: ""
      type: teachings
    values:
      layout: single
      author_profile: true
      share: false
      output: true
      toc: true
      toc_label: "Contents"
      toc_icon: "swatchbook"
      sidebar: main
      classes: wide

sidebar:
  nav: "docs"

author:
  name: "Kenjy KOAN"
  avatar: "/_data/images/photo_cv.jpeg"
  bio: "Data Analyst Supply Chain @Thales SIX GTS France" # Note: Markdown is allowed
  location: "Hauts-de-Seine, France"
  email            : "kenjy.koan@gmail.com"
  github           : "kenjykoan"
  linkedin         : "kenjykoan"

# Site
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
